apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-world.serviceAccountName" . }}
      initContainers:
      {{- if ne $initContainerEnabled "" }}
        - name: "init"
          image: "{{ $initContainerEnabled }}"
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
        - name: redis
          image: redis
          volumeMounts:
            {{- if .Values.redis.enabled }}
            - name: data
              mountPath: /data/redis
              subPath: redisData
            - name: data
              mountPath: /data/tmp
              subPath: tmpData
            - name: data
              mountPath: /data/logs
              subPath: logsData
            {{- end }}
      volumes:
        - name: data
          emptyDir: {}  
